chore : 001-기존 작성된 코드 옮기기(로그인, 회원가입)
Urscent-FE/urscent-web pull request #15
Opened 2022-12-01 04:26 UTC by junvely

## 변경 사항

- 로그인, 회원가입 페이지 기존 작성된 코드 옮기기
- 유효성 검사 등 useMemo를 이용한 리팩토링
- 아이디 유효성 검사 => 이메일 방식으로 변경 및 에러문구 수정(플레이스홀더 미정)
- 비밀번호 입력란에서 대문자, 한글 입력 시 입력방지 처리(입력시 지워짐)
- 타입 스크립트 적용

## 확인이 필요한 부분

- 타입 스크립트 적용이 미숙하여 확인 한번 부탁드립니다.

### 참고 사항

- 없음

2022-12-01 05:15 UTC, iamidlek requested changes
불필요한 파일도 같이 올라온 것 같습니다.
기타 코드에 대한 코멘트와 함께 확인해 주세요.

2022-12-01 05:15 UTC, iamidlek commented on src/pages/SignupPage2.tsx
> +  console.log(password);
개발 환경에서 확인용으로 작성한 console.log는 제거 후 올려주세요,

2022-12-01 05:15 UTC, iamidlek commented on src/pages/SignupPage.tsx
> +        inputRegexCheck={inputRegexCheck}
regex 체크를 input에 넣어서 확인할 필요가 있는지 재 확인이 필요한 것 같습니다.

개인적으로는 input에 useState로 값을 부모 컴포넌트에서 관리하고 있기 때문에
부모 컴포넌트에서 확인 하는 것이 어떨까 싶어요.

2022-12-01 06:10 UTC, junvely commented on src/pages/SignupPage2.tsx
> +  console.log(password);
넵 확인했습니다!

2022-12-01 06:10 UTC, junvely commented on src/pages/SignupPage.tsx
> +        inputRegexCheck={inputRegexCheck}
넵 확인했습니다!

2022-12-06 13:14 UTC, iamidlek approved these changes
확인하였습니다. 고생하셨습니다.

2022-12-06 13:27 UTC, merged